- poc-idev:
    key: ./config/poc-idev.json
    zones:
      us-central1-a:
        instance-1:
          active_hours: 05-12,15-19
          week_day: Mon,Tue,Wed,Thu,Fri,Sat,Sun
        instance-2:
          active_hours: 05-12,15-19
          week_day: Mon,Tue,Wed,Thu,Fri,Sat,Sun
